---
# Here we define final steps for install the latest version of Wordpress
# name - define name of task
# get_url - url - define from where we want to download / dest - where we want to download / validate_certs - if we want validate SSL certificate of source
- name: Downloading latest WordPress installation
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no


# In this step we are extracting wordpress installation, which we download   
- name: Extract downloaded installation
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

# This task set new localadmin directory from default /var/www/html to /var/www/wordpress

- name: Setting new localadmin directory for website
  become: yes
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

# In this task we create new config file with created mysql credentials    

- name: Creating new config file by copying of existing sample file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  become: yes

  #This 3 steps rewrite values in created config file using regular expression and replace

- name: Setting MySQL username
  become: yes
  replace:
    path: "/var/www/wordpress/wp-config.php"
    regexp: "(.*)username_here(.*)$"
    replace: '\1{{ mysql_user }}\2'

- name: Setting MySQL database
  become: yes
  replace:
    path: "/var/www/wordpress/wp-config.php"
    regexp: "(.*)database_name_here(.*)$"
    replace: '\1{{ mysql_database }}\2'

- name: Setting MySQL password
  become: yes
  replace:
    path: "/var/www/wordpress/wp-config.php"
    regexp: "(.*)password_here(.*)$"
    replace: '\g<1>{{ mysql_password }}\g<2>'

