- name: Configure syslog-ng, Apache2 & munin-node op wordpress
  hosts: docker_host
  become: true

  tasks:
    - name: update packed cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Instaleer apache2
      apt:
        name: apache2

    - name: Installeer syslog-ng
      apt:
        name: syslog-ng

    - name: instaleer Munin-node
      apt:
        name: munin-node

      tags:
        - syslog-ng

    - name: Configureer Munin-node
      blockinfile:
        path: /etc/munin/munin-node.conf
        marker: "# {mark} Ansible Managed Node - syslog-ng"
        block: |

          allow ^10.6.0.135$
          host_name docker

    - name: Configure syslog-ng for remote logging
      blockinfile:
        path: /etc/syslog-ng/syslog-ng.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - remote logging"
        block: |
          source s_local {
            system();
            internal();
            file("/var/log/apache2/access.log" flags(no-parse));
            file("/var/log/apache2/error.log" flags(no-parse));
            file("/var/log/munin/munin-node.log" flags(no-parse));
            file("/var/log/munin/munin-update.log" flags(no-parse));
            file("/var/log/syslog" flags(no-parse));
          };
          destination d_net {
            tcp("10.6.0.5" port(514));
          };
          log {
            source(s_local);
            destination(d_net);
          };


    - name: Configure syslog-ng for Munin
      blockinfile:
        path: /etc/syslog-ng/syslog-ng.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - munin"
        block: |
          source s_munin {
            file("/var/log/munin/munin-node.log" flags(no-parse));
            file("/var/log/munin/munin-update.log" flags(no-parse));
          };
          destination d_net {
            tcp("10.6.0.5" port(514));
          };
          log {
            source(s_munin);
            destination(d_net);
          };
      notify:
        - Restart syslog-ng
      tags:
        - syslog-ng
    - name: Configure syslog-ng for system logs
      blockinfile:
        path: /etc/syslog-ng/syslog-ng.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - system logs"
        block: |
          source s_system {
            system();
            internal();
          };
          destination d_net {
            tcp("10.6.0.5" port(514));
          };
          log {
            source(s_system);
            destination(d_net);
          };
      
  handlers:
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted

    - name: Restart syslog-ng
      service:
        name: syslog-ng
        state: restarted

    - name: Restart Munin
      service:
        name: munin-node
        state: restarted

    - name: Print Message
      shell: echo "klaar voor gebruik!"