- name: Hoofdserver configureren
  hosts: localhost
  become: true

  tasks:
    - name: update packed cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: install apache2
      apt:
        name: apache2

    - name: installeer Munin
      apt:
        name: munin
        state: present

    - name: start munin service
      service:
        name: munin
        state: started
        enabled: yes

    - name: Configure apache2 
      blockinfile:
        path: /etc/apache2/apache2.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - apache2 hardening"
        block: |
          ServerTokens Prod
          ServerSignature Off
          FileETag None

    - name: Node toevoegen
      blockinfile:
        path: /etc/munin/munin.conf
        marker: " {mark} Ansible Managed Block - Node toevoegen"
        block: |

          [docker]
                  address 10.6.0.137

          [wordpress]        
                  address 10.6.0.138
                  
    - name: permission munin
      shell: sed -i 's/Require local/Require all granted/g' /etc/munin/apache24.conf && sed -i 's/Options None/Options FollowSymLinks SymLinksIfOwnerMatch/g' /etc/munin/apache24.conf

      notify:
        - Restart apache2
        - Restart munin
    - name: Configure syslog-ng for local logs
      blockinfile:
        path: /etc/syslog-ng/syslog-ng.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - local logs"
        block: |
          source s_local {
            file("/var/log/apache2/access.log" flags(no-parse));
            file("/var/log/apache2/error.log" flags(no-parse));
            file("/var/log/munin/munin-node.log" flags(no-parse));
            file("/var/log/munin/munin-update.log" flags(no-parse));
            file("/var/log/syslog" flags(no-parse));
          };
          destination d_logs {
            file("/var/log/syslog-ng");
          };
          log {
            source(s_local);
            destination(d_logs);
          };
    - name: Restart syslog-ng service
      service:
        name: syslog-ng
        state: restarted
      become: yes

  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted

    - name: Restart munin
      service:
        name: munin
        state: restarted